#ifndef VIEWTYPE
#define VIEWTYPE

enum ViewType{UNKNOWN,
             ANALYST_SELECTION_VIEW, MAIN_MENU_VIEW, METADATA_VIEW, WORKPLACELIST_VIEW,
             WORKPLACE_VIEW, LINE_VIEW, ACTIVITY_VIEW, COMMENT_VIEW, DOCUMENTATION_VIEW,
             RESSOURCE_MANAGMENT_VIEW, EQUIPMENT_VIEW, TRANSPORTATION_VIEW,
             SHIFT_VIEW, SETTINGS_VIEW, PRODUCT_VIEW, FEEDBACK_VIEW};

#endif // VIEWTYPE

