#ifndef VIEWTYPE
#define VIEWTYPE

enum ViewType{UNKNOWN,
             ANALYST_SELECTION_VIEW, MAIN_MENU_VIEW, METADATA_VIEW, WORKPLACELIST_VIEW,
             WORKPLACE_VIEW, LINE_VIEW, ACTIVITY_VIEW, COMMENT_VIEW, DOCUMENTATION_VIEW,
             RESSOURCE_MANAGMENT_VIEW, EQUIPMENT_VIEW, TRANSPORTATION_VIEW,
             SHIFT_VIEW, SETTINGS_VIEW, PRODUCT_VIEW, EMPLOYEE_VIEW, EMPLOYEE_LIST_VIEW,
             BODY_MEASUREMENT_VIEW, SHIFT_CALENDAR_VIEW, ROTATION_GROUP_VIEW, ROTATION_GROUP_LIST_VIEW,
             GANT_VIEW, BODY_POSTURE_VIEW, APPLIED_FORCE_VIEW, WORKING_CONDITION_VIEW,
             LOAD_HANDLING_VIEW, WORK_PROCESS_META_DATA_VIEW};
enum PopUpType{ANALYST_POPUP,
               ACTIVITY_POPUP, CREATE_PRODUCT_POPUP, EQUIPMENT_POPUP, TRANSPORTATION_POPUP,
<<<<<<< HEAD
               FEEDBACK_POPUP, DB_SEND_POPUP, LANGUAGE_POPUP, THEME_POPUP, WORKPLACE_POPUP,
               IMPORT_DATA_POPUP, RESET_POPUP, EMPLOYEE_POPUP, CAMERA_POPUP, FACTORYSETTINGS_POPUP, LINE_POPUP};
=======
               DB_SEND_POPUP, LANGUAGE_POPUP, THEME_POPUP, WORKPLACE_POPUP,
               IMPORT_DATA_POPUP, RESET_POPUP, EMPlOYEE_POPUP, CAMERA_POPUP, FACTORYSETTINGS_POPUP, LINE_POPUP};
>>>>>>> origin/Unstable

#endif // VIEWTYPE

